title: 赵大叔的学习笔记
author: 赵何宇
email: zhaoheyvv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The light which puts out our eyes is darkness to us. Only that day dawns to which we are awake. There is more day to dawn. The sun is but a morning star.
github_username:  zhaoheyv
permalink: /:year/:month/:title/
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
highlighter: rouge

